# Generated by Django 4.1.5 on 2023-01-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tirik', models.CharField(default='ha', max_length=50)),
                ('kitob_soni', models.PositiveIntegerField()),
                ('jinsi', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=50)),
                ('tugulgan_sana', models.DateField()),
            ],
        ),
    ]
