# Generated by Django 4.1.5 on 2023-01-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('bitiruvchi', models.CharField(choices=[('ha', 'ha'), ('yoq', 'yoq')], max_length=50)),
                ('kitoblar_soni', models.PositiveIntegerField(default=0)),
                ('kurs', models.PositiveIntegerField()),
            ],
        ),
    ]
