# Generated by Django 4.1.5 on 2023-01-10 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sahifa', models.PositiveIntegerField()),
                ('muallif', models.CharField(max_length=100)),
                ('janr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.muallif')),
            ],
        ),
    ]
