# Generated by Django 4.1.5 on 2023-01-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_kitob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='janr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.muallif'),
        ),
    ]
