# Generated by Django 4.1.5 on 2023-01-10 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0007_nashriyot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.BigIntegerField()),
                ('kelgan_sana', models.DateField()),
                ('nashriyot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.nashriyot')),
            ],
        ),
    ]
